Repository sugiartofahmi/react-surveyform, pull requests merged in 2022-11, with the labels that each got.

#4 Maulana Sodiqin | Add Supabase Connection
  package-lock.json
  package.json
  src/supabase.ts
  yarn.lock
Labels: enhancement, good first issue

#5 Fahmi Sugiarto | Add Radio Button
  src/components/Form/index.jsx
  src/components/Radio/index.jsx
Labels: enhancement

#6 Fahmi Sugiarto | Add Select Option
  src/components/Form/index.jsx
  src/components/Select/index.jsx
  src/components/TextField/index.jsx
Labels: enhancement

#7 Fahmi Sugiarto | Fix Select Option
  src/components/Form/index.jsx
  src/components/Select/index.jsx
Labels: bug, enhancement
